spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #swagger高版本

mybatis:
  type-aliases-package: com.auggie.student_server.entity
  mapper-locations: classpath:mapper/*.xml


server:
  port: 10085
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
