spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentms?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: 123456
#  messages: #国际化配置
#    basename: i18n/msg

msg-baseName: i18n/msg

server:
  port: 10087


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.auggie.student_server.entity
  mapper-locations: classpath:mapper/*.xml